ci:
  autoupdate_schedule: monthly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-json
        exclude: ^.devcontainer/
      - id: check-yaml

  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 26.5.1
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/keewis/blackdoc
    rev: v0.4.6
    hooks:
      - id: blackdoc
        additional_dependencies: ["black==26.5.1"]
      - id: blackdoc-autoupdate-black

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.20
    hooks:
      - id: ruff-check
        args: ["--fix", "--show-fixes"]

  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.9.4
    hooks:
      - id: prettier
        args: ["--cache-location=.prettier_cache/cache"]

  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
        args: ["--option", "array_auto_collapse=false"]
      - id: taplo-lint
        args: ["--no-schema"]

  - repo: https://github.com/kynan/nbstripout
    rev: 0.9.1
    hooks:
      - id: nbstripout
        args: [--extra-keys=metadata.kernelspec metadata.language_info.version]
