name: "Setup Pixi"
description: "Create Python environment for GitHub Action Job"

runs:
  using: "composite"
  steps:
    - uses: prefix-dev/setup-pixi@v0.8.10
      with:
        manifest-path: pyproject.toml
        cache: true
        activate-environment: true
